//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBenXe
    {
        public tblBenXe()
        {
            this.tblChiTietTuyens = new HashSet<tblChiTietTuyen>();
            this.tblTuyenXes = new HashSet<tblTuyenXe>();
            this.tblTuyenXes1 = new HashSet<tblTuyenXe>();
        }
    
        public string MaBenXe { get; set; }
        public string TenBenXe { get; set; }
    
        public virtual ICollection<tblChiTietTuyen> tblChiTietTuyens { get; set; }
        public virtual ICollection<tblTuyenXe> tblTuyenXes { get; set; }
        public virtual ICollection<tblTuyenXe> tblTuyenXes1 { get; set; }
    }
}
