//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeXePhuongTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThamSo
    {
        public int MaThamSo { get; set; }
        public Nullable<int> ThoiGianDiToiThieu { get; set; }
        public Nullable<int> BenXeTrungGianToiDa { get; set; }
        public Nullable<int> ThoiGianDungToiThieu { get; set; }
        public Nullable<int> ThoiGianDungToiDa { get; set; }
    }
}
